print("The time has come,' the Walrus said,")
print("'Twas brillig, and the slithy toves")
print("To talk of many things:")
print("Did gyre and gimble in the wabe:")
print("Of shoes — and ships — and sealing-wax —")
print("All mimsy were the borogoves, ")
print("Of cabbages — and kings —")
print("And the mome raths outgrabe. ")
print("And why the sea is boiling hot —")
print("O frabjous day! Callooh! Callay!")
print("And whether pigs have wings.'")