'''
Programming 101
Unit 5
'''

import random
import string # string module

letters = string.ascii_letters
# print(letters) # abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ

digits = string.digits
# print(digits) # '0123456789'

punctuation = string.punctuation
# print(punctuation) # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

all_characters = letters + digits + punctuation
# print(all_characters) # abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

# --------------------------------------------------------------------------------------------------- #

# while loop

'''
while some_condition == True:
    # loop this code block
    # until 'some_condition'
    # becomes False
'''

# "for x in range(10)" with a while loop

x = 0

while x < 10:
    # print(x)

    # ... other code

    # increment x to eventually make the loop's condition False
    x += 1

# --------------------------------------------------------------------------------------------- #

# generate a list of 10 random numbers between 0 and 100

# blank list to store numbers
numbers = []

# loop until there are 10 numbers in the list
while len(numbers) < 10:
    # add a random number to the list
    numbers.append(random.randint(0, 100))

# print(numbers) # [90, 3, 61, 23, 22, 94, 75, 9, 17, 48]

# ------------------------------------------------------------------------------ #

# string pattern builder - run a loop to create an alternating pattern of string characters

# blank string to hold the pattern
pattern = ''

while len(pattern) <= 10:

    # check if the pattern's length is even
    if len(pattern) % 2 == 0:
        pattern += '*'

    # check if the pattern's length is odd
    elif len(pattern) % 2 == 1:
        pattern += '-'

# print(pattern) # *-*-*-*-*-*

# ------------------------------------------------------------------------------ #

# remove one number at time from a list until the list is empty

# generated by the loop on line 52
# print(numbers)

# loop while the list still has numbers in it
while numbers != []:
    # remove one item from the end of the list and save it in a variable
    number = numbers.pop()

    # print(number, numbers)

# -------------------------------------------------------------------------------- #

# loop controls
# else, break, continue

for x in range(10):

    if x == 3 or x == 5:
        print(x * '.')
        continue # skip the rest of this iteration and begin the next

    if x == 8:
        print('Goodbye')
        break # end the loop immediately
    
    print(x)

else:
    # else will be triggered
    # if the loop's condition becomes False
    print('The loop made it all the way through!')

print("\nother code ...")